### ISSUE TITLE
Empty assembly view

### ISSUE THREAD

**Issue by stephane-caron** [AndReGeist/wheelbot-v2.5#1]
Thank you for making this awesome open source project :smiley: 

This is a quick heads up that the assembly view PDF in ``CAD files/`` is empty.

**Comment by AndReGeist** [comment]
Thanks for the heads up! If you open the file with adobe acrobat and click on "Enable multimedia content" then you can see the interactive assembly. Otherwise, the file indeed appears to be empty.
